// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "82df9b38-b1b1-4893-9fb7-690bfdc5db13";

const char SSID[]               = "Wifi andrei";    // Network SSID (name)
const char PASS[]               = "12345678";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "qKzuOR6PP!CLvLey@7#C6WZLf";    // Secret device password

void onVolumeBuzzerChange();
void onEstadoBuzzerChange();
void onEstadoLedsChange();
void onEstadoServoChange();

int volume_buzzer;
bool estado_buzzer;
bool estado_leds;
bool estado_servo;
bool movimento_detectado;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(volume_buzzer, READWRITE, ON_CHANGE, onVolumeBuzzerChange);
  ArduinoCloud.addProperty(estado_buzzer, READWRITE, ON_CHANGE, onEstadoBuzzerChange);
  ArduinoCloud.addProperty(estado_leds, READWRITE, ON_CHANGE, onEstadoLedsChange);
  ArduinoCloud.addProperty(estado_servo, READWRITE, ON_CHANGE, onEstadoServoChange);
  ArduinoCloud.addProperty(movimento_detectado, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
